### ISSUE TITLE
Options in autoload

### ISSUE THREAD

**Issue by svensp** [LucHermitte/alternate-lite#1]
Having the following setting causes errors in the vimrc, after/plugin/xxx.vim and even in after/ftplugin/cpp/xxx.vim
```
let g:alternates.searchpath = 'sfr:.:
```

I believe this is because the options are set in the `autoload/lh/alternate.vim` so they are only created once a function from this file is called - after :GOTOIMPL
From what I could gather options should be set in `plugin/alternate.vim` instead so they can be overwritten before the first function call. A quick hack worked for me but I don't know enough about vimscript to make a quality pull request.

**Comment by LucHermitte** [comment]
Hi.

Just to be sure, have you done a `let g:alternates = {}` beforehand? It's the only prerequisite to the line you've defined in your `.vimrc`. (`runtime autoload/lh/alternate.vim` may be enough as well)

Or your could also write: `let g:alternates = {'searchpath': 'sfr:.:'}` or (after your plugin manager has updated the `&runtimepath`):
```vim
runtime plugin/let.vim " only necessary in the vimrc
LetIfUndef g:alternates.searchpath = 'sfr:.:
" or if you prefer to override the option when/if you reload your .vimrc:
LetTo g:alternates.searchpath = 'sfr:.:
```

I'll have to update the documentation ^^'

**Comment by svensp** [comment]
Ah no, I didn't know how to do that.
I tried to adapt from the extension map documentation to actually append `,sfr:.` to the searchpath but setting it like that works for me.
Thanks!

**Comment by LucHermitte** [comment]
It's my mistake to expect newcomers to viml to know how dictionaries works -- and sometimes how `&rtp`  can be used to define options.
