### ISSUE TITLE
Alternate to file with an existing swap file gives errors

### ISSUE THREAD

**Issue by fwsmit** [LucHermitte/alternate-lite#2]
Not sure if there is still development on this plugin. This is a minor bug, but I'll mention it anyway.
When you have file foo.cpp open in vim and you type :AS to move to the header file vim will throw errors if the header file already has an existing swap file. The errors it gives are:

```
Error detected while processing function 
lh#alternate#_jump[35]..lh#buffer#jump[3]..lh#window#create
_window_with:
line    2:
E325: ATTENTION
Error detected while processing function lh#alternate#_jump:
line   35:
E171: Missing :endif
```

**Comment by LucHermitte** [comment]
All my plugins are under development actually :)

Here, I was aware of the bug as I've observed it in many other places. So far I've never took the time to properly investigate what I could do. I guess I'll have to ask for help on vim-dev mailing list on this one.

**Comment by LucHermitte** [comment]
Unless you choose to "quit" when loading a file with an already existing swap file, the error message shall disappear now.
It requires to update lh-vim-lib -- if you confirm the resolution, I'll tag a new version of lh-vim-lib.
